tcp_ik_solver:
  ros__parameters:
    tcp_file: /home/wonny/ur3_control/src/ROS2_MuJoCo_UR3/src/ur3_rl_bridge/config/tcp/gripper_tip.yaml
    base_frame: base_link
    planning_group: ur_manipulator
    ik_link_name: tool0
    avoid_collisions: true
    ik_timeout_sec: 2.0
    execute_motion: true
    # moveit = collision-aware route planning, controller = direct joint command without route planning.
    execute_mode: moveit
    move_group_action: /move_action
    planning_time_sec: 20.0
    planning_attempts: 8
    joint_goal_tolerance_rad: 0.01
    velocity_scale: 0.2
    acceleration_scale: 0.20
    trajectory_action: /joint_trajectory_controller/follow_joint_trajectory
    motion_duration_sec: 3.0
    manipulator_joint_names:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    # If use_config_target is false, the node asks for these values in the terminal.
    # If true, it uses target_tcp_xyz and lookat_vector below.
    use_config_target: true
    target_tcp_xyz: [0.30, -0.350, 0.04]
    lookat_vector: [0.0, 0.0, -1.0]
    # Rotate gripper around the look-at axis. 1.5708 rad = 90 deg.
    tcp_roll_rad: 1.5708
