<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ur3_isaac_nitros_bridge</name>
  <version>0.0.1</version>
  <description>ROS sensor_msgs to Isaac Nitros relays for FoundationPose</description>
  <maintainer email="wonny@todo.todo">wonny</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rclcpp_components</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>sensor_msgs</depend>
  <depend>isaac_ros_managed_nitros</depend>
  <depend>isaac_ros_nitros</depend>
  <depend>isaac_ros_nitros_image_type</depend>
  <depend>isaac_ros_nitros_camera_info_type</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
