controller_manager:
  ros__parameters:
    update_rate: 25

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController

position_controller:
  ros__parameters:
    joints:
      - actuator1
      - actuator2
      - actuator3
      - actuator4
      - actuator5
      - actuator6

